name: Build and Release whisper-cli

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Clone whisper.cpp and build binary
        run: |
          git clone https://github.com/ggerganov/whisper.cpp.git
          cd whisper.cpp
          mkdir build
          cd build
          cmake ..
          make

      - name: Upload binary to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: whisper-cli
          tag_name: ${{ github.ref_name }}
          files: whisper.cpp/build/whisper-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
