name: Build and Release whisper-cli

on:
  push:
    tags:
      - 'v*'        # Trigger on tags like v1.0.0
  workflow_dispatch: # Allow manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Clone whisper.cpp
        run: |
          git clone https://github.com/ggerganov/whisper.cpp.git
          cd whisper.cpp
          mkdir build && cd build
          cmake ..
          make
          cp whisper-cli ../../whisper-cli

      - name: Upload whisper-cli as release asset
        uses: softprops/action-gh-release@v2
        with:
          files: whisper-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
