name: Build whisper-cli

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git

      - name: Clone whisper.cpp repo inside server folder
        run: git clone https://github.com/ggerganov/whisper.cpp.git server/whisper.cpp

      - name: Build whisper-cli binary
        working-directory: server/whisper.cpp
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Upload whisper-cli artifact
        uses: actions/upload-artifact@v3
        with:
          name: whisper-cli
          path: server/whisper.cpp/build/whisper-cli
